name: Manual Sync with Upstream (+Tags)

on:
  workflow_dispatch:

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Configure Git to use the GitHub Actions token
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream repository as a remote
        run: git remote add upstream https://github.com/xenocrat/chyrp-lite.git

      - name: Fetch all branches and tags from upstream
        run: git fetch upstream

      - name: Checkout the default branch
        run: git checkout master

      - name: Merge changes from upstream default branch
        run: git merge upstream/master --ff-only

      - name: Push changes to the default branch on fork
        run: git push origin master

      - name: Push tags from upstream to fork
        run: git push origin --tags

      - name: Remove upstream remote (cleanup)
        run: git remote remove upstream

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
